<?php echo $this->doctype(); ?>

<html lang="es">


     <head>
        <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

 <title>Nanopharmacia</title>


 <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/nano.ico'))

                        ->prependStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/plugins/morris.css')
                        ->prependStylesheet($this->basePath() . '/css/sb-admin-2.css')
                        ->prependStylesheet($this->basePath() . '/css/plugins/timeline.css')
                        ->prependStylesheet($this->basePath() . '/css/plugins/metisMenu/metisMenu.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap2.min.css')


                        ?>
                        <script src="<?php echo $this->basePath()?>/js/jquery-1.11.0.js"></script>
<script src="<?php echo $this->basePath()?>/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath()?>/js/plugins/metisMenu/metisMenu.min.js"></script>
<script src="<?php echo $this->basePath()?>/js/plugins/morris/raphael.min.js"></script>
<script src="<?php echo $this->basePath()?>/js/sb-admin-2.js"></script>




       <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


    </head>

<body>

    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath()?>"><img src="<?php echo $this->basePath()?>/img/instituciones/1-freemind.png" style="height:50px"></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">

                </li>

                <!-- /.dropdown -->
                <style type="text/css">
                .red {
                    color:red;
                }
                </style>
            <!--   <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-lg red"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-briefcase fa-lg"></i> 1 Seguimientos Pendientes
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-lg"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-lg"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-lg"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-lg"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>

                </li> -->
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-lg"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                        <ul class="dropdown-menu dropdown-user">
                        <li><a href="<?php echo $this->basePath()?>/administrador/index/editar"><i class="fa fa-user fa-lg"></i> Perfil del Usuario</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-lg"></i> Configuración</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->basePath()?>/administrador/index/logout"><i class="fa fa-sign-out fa-lg"></i> Cerrar sesión</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="<?php echo $this->basePath();?>/administrador"><i class="fa fa-home fa-lg"></i> Inicio </a>
                        </li>
                        <?php if($this->SeccionSeguimiento>0){ ?>
                         <li>
                            <a><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> Seguimientos<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level collapse" aria-expanded="true">

                              <?php if($this->Seg_pendientes>0){?>

                              <?php @$count= $identi[0][id_seg] ?>
                              <!--
                              <?php //if($this->Seg_pendiente==0){?>
                              <?php //$count= $identi[0][id_seg] ?>
 -->
                              <li>
                                  <a href="<?php echo $this->basePath()?>/seguimiento/index/pendiente">
                                    <?php if ($count=='1') { ?>
                                    Seguimiento pendiente  <span class="badge"><?php echo $count ?></span><?php
                                  }else {?>
                                    Seguimientos pendientes  <span class="badge"><?php echo $count ?></span><?php
                                  } ?>
                                  </a>
                              </li>
                              <?php } ?>
                              <?php if($this->Seg_nuevo>0){?>
                              <li>
                                  <a href="<?php echo $this->basePath()?>/seguimiento/index/concluidos"> Seguimientos finalizados</a>
                              </li>
                              <?php } ?>
                            </ul>
                        </li>
                        <?php }?>
                        <!--<?php //if($this->SeccionReportes>0){ ?>-->
                        <!--<li>
                            <a><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Reportes<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level collapse" aria-expanded="true">-->
                                <!--<?php //if($this->Rep_Producto>0){?>-->
                                <!-- <li>
                                    <a href="<?php echo $this->basePath()?>/reportes"> Productos</a>
                                </li> -->
                                <!--<?php //} ?>-->
                                <!--<?php //if($this->Rep_Facturas>0){?>-->
                              <!--   <li>
                                    <a href="<?php echo $this->basePath()?>/reportes/index/productsreport"> Facturas</a>
                                </li> -->
                                <!--<?php //} ?>-->
                            <!--</ul>
                            
                        </li>-->
                        <!--<?php //}?>-->
                        <?php if($this->SeccionCatalogos>0){?>
                        <li>
                            <a><span class="glyphicon glyphicon-folder-open" aria-hidden="true"> </span> Catalogos<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level collapse" aria-expanded="true">
                                <?php if($this->Cat_Clie>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo">Clientes</a></li>
                                <?php }?>
                                <!--<?php //if($this->Cat_Area>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/catarea">Áreas</a></li> -->
                                <!--<?php //}?>-->
                                <!--<?php //if($this->Cat_Banc>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/catbancos">Bancos</a></li> -->
                                <!--<?php //}?>-->
                                <!--<?php //if($this->Cat_UMed>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/catunimed">Unidades de medida</a></li> -->
                                <!--<?php //}?>-->
                                <!--<?php //if($this->Cat_Sect>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/catsectores">Sectores</a></li> -->
                                <!--<?php //}?>-->
                                <?php if($this->Cat_User>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo/index/catusuarios">Usuarios</a></li>
                                <?php }?>
                                <?php if($this->Cat_Psto>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo/index/catpuestos">Puestos</a></li>
                                <?php }?>
                                <?php if($this->Cat_Muni>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo/index/catmunicipios">Municipios</a></li>
                                <?php }?>
                                <?php if($this->Cat_Loca>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo/index/catlocalidades">Localidades</a></li>
                                <?php }?>
                                <!--<?php //if($this->Cat_Cotc>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/catcontactosasc">Contacto</a></li> -->
                                <!--<?php //}?>-->
                                <?php if($this->Cat_Sucr>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo/index/catsucursales">Sucursales</a></li>
                                <?php }?>
                                <?php if($this->Cat_Prdd>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo/index/catpropiedades">Propiedades</a></li>
                                <?php }?>
                                <?php if($this->Cat_Epls>0){?>
                                <li><a href="<?php echo $this->basePath()?>/catalogo/index/empleadoscata">Empleados</a></li>
                                <?php }?>

                                <!-- Pendiente de desarrollo -->
                                <li><a href="<?php echo $this->basePath()?>">Estudios <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span></a></li>
                                <li><a href="<?php echo $this->basePath()?>">Servicio de Paqueteria <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span</a></li>

                                <!-- Fin pendiente de desarrollo -->


                                <!--<?php //if($this->Cat_Clie>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/lineascata">Lineas</a></li> -->
                                <!--<?php //}?>-->
                                <!--<?php //if($this->Cat_Prvd>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/provedorescata">Proveedores</a></li> -->
                                <!--<?php //}?>-->
                                <!--<?php //if($this->Cat_PdTr>0){?>-->
                                <!-- <li><a href="<?php echo $this->basePath()?>/catalogo/index/productosterminadoscata">Productos Terminados</a></li> -->
                                <!--<?php //}?>-->

                            </ul>
                            <!-- /.nav-third-level -->
                        </li>
                        <?php }?>


                        <li>
                            <a><span class="glyphicon glyphicon-leaf" aria-hidden="true"> </span>  Muestras<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level collapse" aria-expanded="true">                                
                                <li><a href="<?php echo $this->basePath()?>/muestra">Registro de muestras</a></li>  
                                <li><a href="<?php echo $this->basePath()?>/muestra">Muestras activas</a></li>
                                <li><a href="<?php echo $this->basePath()?>/muestra">Muestras inactivas</a></li>
                            </ul>
                        </li>



                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->


        </nav>

        </style>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header"> Nanopharmacia</h4>

                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.contedido cpanel-->
            <div class="container">
                <div id="contenido">
                    <?php echo $this->content; ?>
                </div>

            <!-- /.cierra contenido-->
            </div>
            <!-- /#page-wrapper -->

        </div>
    <!-- /#wrapper -->
    <style type="text/css">
    nav.navbar.navbar-default.navbar-static-top {
        height: 78px;
        }
.hidden {
  display: none !important;
  visibility: hidden !important;
}
    </style>


</body>

</html>
