<?php
//Preparamos el formulario
$form = $this->form;
$form->prepare();

//Definimos el atributo action y method
$form->setAttributes(array(
    'action' => $this->url,
    'method' => 'post',
    'class'  => 'form-signin'
));

//Utilizamos el plugin para mostrar los label
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>

<h2 class="form-signin-heading">Iniciar Sesión</h2>
<div class="form_element">
<?php
    //Imprimimos el campo usuario
    $nombre = $form->get('nombre');
    echo $this->formInput($nombre);
    echo $this->formElementErrors($nombre);
    echo $formLabel->closeTag();
?>
</div>


<div class="form_element">
<?php
    //Imprimimos el campo contraseña
    $pass = $form->get('pass');
    echo $this->formInput($pass);
    echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
?>
</div>

<button class="btn btn-lg btn-primary btn-block" type="submit">Aceptar</button>
<?php
//Cerramos el formulario
echo $this->form()->closeTag();
 ?>


 <?php if($this->mensaje) {?>
 </div class="row">
 	<div class="col-md-4 col-md-offset-4">
 		<div class="alert alert-warning" role="alert">
 			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 			<p class="text-center"><?php foreach ($this->mensaje as $error) {
 			  echo $error;?><br>
 			<?php };?></p>
 		</div>
 	</div>
 </div>
 <?php }?>
 <?php if($this->error) {?>
 </div class="row">
   <div class="col-md-4 col-md-offset-4">
     <div class="alert alert-danger" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <p class="text-center"><?php echo ($this->error) ?></p>
     </div>
   </div>
 </div>
 <?php }?>
