<div class="mobile">
  <div class="container">
    <div class="row">
      <div class="box clearfix">
        <h2 class="text-center">Catálogo de usuarios del sistema</h2><br>
        <div class="col-md-2">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ModalForm" onclick="modal('agregar','null')"><span class="glyphicon glyphicon-plus-sign"></span> Agregar </button>
        </div>
        <table class="table table-hover" id="bootstrap-table" >
          <thead>
            <tr>
              <th class="text-center">Nombre de empleado </th>
              <th class="text-center">Usuario</th>
              <th class="text-center">Estatus</th>
              <th class="text-center">Permisos</th>
              <th class="text-center">Ver</th>
            </tr>
          </thead>
          <?php foreach ($this->InfUsuario as  $Usr) { ?>
          <tbody>
            <tr>
              <td class="text-center" style="text-transform : capitalize"><?php echo $Usr['NombreEmpleado']." ".$Usr['ApeEmpleado']?></td>
              <td class="text-center"><?php echo $Usr['NombreUsuario']?></td>
              <td class="text-center"><?php echo ($Usr['EstatusUsuario']=='1')?"Activo":"Inactivo" ?></td>
              <td class="text-center" style="text-transform : capitalize">Permisos</td>
              <td class="text-center"><a data-toggle="modal" data-target="#ModalForm" onclick="modal('editar','<?php echo $Usr['idCat_Usuarios']?>')"><p class="text-center"><span class="glyphicon glyphicon-eye-open"></span></p></a></td>
            </tr>
          </tbody>
          <?php } ?>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- MODAL -->
<div class="modal fade " id="ModalForm" tabindex="-1" role="dialog" >
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="tituloModal"></h4>
      </div>
      <div class="modal-body">
        <form id="FormUsuario" name="FormUsuario" enctype="multipart/form-data" method="post" accept-charset="utf-8" >
          <div class="row">
            <div class="form-group">
              <div class="form-group col-md-8 col-md-offset-2">
                <label for="recipient-name" class="control-label">Nombre de empleado* :</label>
                <input type="text" class="form-control " name="empleado" list="empleado" placeholder=""  required id="Emp">
                <datalist id="empleado">
                </datalist>
                <input type="text" name="id_empleado" value="" id="id_empleado" hidden>
              </div>
            </div>
            <div class="form-group">
              <div class="form-group col-md-5">
                <label for="recipient-name" class="control-label">Usuario* :</label>
                <input type="text" class="form-control" name="NombreUsuario" id="NombreUsuario" required>
              </div>
              <div class="form-group col-md-5">
                <label for="recipient-name" class="control-label">Contraeña* :</label>
                <input type="password" class="form-control" name="PassUsuario" id="PassUsuario" required>
              </div>
              <div class="form-group col-md-2" style="text-align : center" id="Est_usr">
                <label for="recipient-name" class="control-label">Activo :</label>
                <center><input type="checkbox" class="form-control" style="width:23px" name="EstatusUsuario" value="1" id="EstatusUsuario" checked></center>
              </div>
              <input type="hidden" name="FechaAltaUsuario" value="<?php echo date("Y-m-d H:i:s");?>">

            </div>
          </div>
          <input type="text" name="usuario_edit"  id="usuario_edit" hidden>
          <input type="text" name="id_usuario" id="id_usuario" hidden>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary" id="btn-send" onclick="">Agregar</button>
        <button type="submit" class="btn btn-primary" id="btn-edit" >Editar</button>
      </div>
      </form>
    </div>
  </div>
</div>
<!-- END MODAL-->

<script src="<?php echo $this->basePath()?>/js/Catalogos/CatUsuarios.js"></script>

<style media="screen">
.mobile {
  margin-top: 3%;
}

@media screen and  (max-width : 768px){
  .mobile{
    margin-top: 25%;
  }

@media screen and (max-width : 768px) and (orientation : landscape){
    .mobile{
      margin-top: 12%;
    }
}


@media screen  and  (min-device-width : 768px) and (max-device-width : 1024px){
    .mobile{
      margin-top: 7%;
    }

}
@media screen and (min-device-width: 1024px) and (orientation : landscape){
    .mobile{
      margin-top: 3%;
    }
}

</style>
