<div class="row" style="margin-top : 10%">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="panel panel-default" >
      <div class="panel-heading"> <h2 class="panel-title text-center"><span class="glyphicon glyphicon-user" aria-hidden="true"> Bienvenido <span class="glyphicon glyphicon-user" aria-hidden="true"></h2>
      </div>
      <div class="panel-body" style="text-align:center">
        <p class="text-center" ></span></p>
        <p>Usuario : <strong><?php echo $this->Usuario?></strong> </p>
        <p>Nombre : <strong><?php echo $this->Empleado[0]['NombreEmpleado']?></strong></p>
        <p>Apellidos : <strong><?php echo $this->Empleado[0]['ApeEmpleado']?></strong></p>

      </div>
    </div>
  </div>
</div>
